version: "3.8"
services:
  java-app:
    build: .
    image: java-app:latest
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf